driver:
  require_chef_omnibus: <%= ENV.fetch("CHEF_VERSION", "latest") %>
  ssh_key: <%= File.expand_path("./test/support/keys/vagrant") %>
  name: vagrant
  provider: vmware_fusion

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: base
    run_list:
      - recipe[ubuntu-base]
    data_bags_path: test/support/data_bags
    attributes:
      ubuntu-base:
        enable_minitest: false
