name             "ubuntu-base"
maintainer       "Phil Cohen"
maintainer_email "github@phlippers.net"
license          "MIT"
description      "Chef cookbook to bootstrap an opinionated Ubuntu base image"
long_description IO.read(File.join(File.dirname(__FILE__), "README.md"))
version          "0.2.0"

recipe "chef", "Configure Chef client"
recipe "datadog", "Configure Datadog integration"
recipe "default", "Default recipe"
recipe "development", "Install packages for development (ruby, nodejs, etc.)"
recipe "environment", "Configure system environment"
recipe "iptables", "Configure system firewall"
recipe "logging", "Configure system logging components"
recipe "mailer", "Configure system mail relay"
recipe "monitoring", "Configure system monitoring services"
recipe "motd", "Configure system MOTD"
recipe "packages", "Install and purge system packages"
recipe "security", "Configure system security components"
recipe "shell", "Configure shell components"

supports "ubuntu"

depends "afw"
depends "brightbox-ruby"
depends "build-essential"
depends "chef-client"
depends "chef-sugar"
depends "chkrootkit"
depends "datadog"
depends "fail2ban"
depends "grc"
depends "hostname"
depends "htop"
depends "locale"
depends "logrotate"
depends "logwatch"
depends "minitest-handler"
depends "newrelic-sysmond"
depends "nodejs"
depends "ntp"
depends "omnibus_updater"
depends "openssh"
depends "papertrail"
depends "postfix"
depends "resolver"
depends "rkhunter"
depends "sudo"
depends "sysctl"
depends "sysstat"
depends "timezone"
depends "tmux"
depends "ubuntu"
depends "unattended-upgrades"
depends "users"
depends "zsh"
